#!/bin/sh

##
# Copyright (c) 2005-2014 Apple Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

set -e
set -u

wd="$(cd "$(dirname "$0")" && pwd)";

if [ -n "${PYTHON:-}" ]; then
  python="${PYTHON}";
else
  python=python;
fi;

##
# Enable development mode
##

dev_root="${wd}/.develop";
dev_libdir="${dev_root}/lib";
dev_bindir="${dev_root}/bin";

mkdir -p "${dev_root}";
mkdir -p "${dev_libdir}";

export PYTHONPATH="${dev_libdir}:${PYTHONPATH:-}"

cd "${wd}";

if ! ./setup.py develop  \
  --install-dir "${dev_libdir}"   \
  --script-dir "${dev_bindir}"    \
  > "${dev_root}/setup.log" 2>&1; then
  err=$?;
  echo "Unable to set up for development:"
  cat "${dev_root}/setup.log";
  exit ${err};
fi;
