#!/usr/bin/env bash

wd="$(cd "$(dirname "$0")" && pwd)";

if [ -n "${PYTHON:-}" ]; then
  python="${PYTHON}";
else
  python=python;
fi;

export PYTHONPATH="${wd}:${PYTHONPATH:-}";

exec "${python}" "$@";
